import { Account, CompanyProfile, InventoryItem, JournalEntry, Transaction } from '../types';

export function generateStandardChartOfAccounts(companyId: string, entityType: string): Account[] {
  return [
    // ASSETS (1000 - 1999)
    {
      id: `${companyId}-acc-1010`,
      companyId,
      code: '1010',
      name: 'Operating Checking Account',
      type: 'Asset',
      subtype: 'Cash & Bank',
      normalBalance: 'Debit',
      description: 'Primary business operating bank account',
      isActive: true,
      isSystem: true,
    },
    {
      id: `${companyId}-acc-1020`,
      companyId,
      code: '1020',
      name: 'High-Yield Savings & Reserve',
      type: 'Asset',
      subtype: 'Cash & Bank',
      normalBalance: 'Debit',
      description: 'Tax and emergency cash reserve account',
      isActive: true,
    },
    {
      id: `${companyId}-acc-1030`,
      companyId,
      code: '1030',
      name: 'Accounts Receivable (A/R)',
      type: 'Asset',
      subtype: 'Accounts Receivable',
      normalBalance: 'Debit',
      description: 'Customer invoices owed to company',
      isActive: true,
      isSystem: true,
    },
    {
      id: `${companyId}-acc-1050`,
      companyId,
      code: '1050',
      name: 'Merchandise Inventory',
      type: 'Asset',
      subtype: 'Inventory',
      normalBalance: 'Debit',
      description: 'Goods available for sale',
      isActive: entityType === 'Corporation' || entityType === 'Partnership',
    },
    {
      id: `${companyId}-acc-1080`,
      companyId,
      code: '1080',
      name: 'Prepaid Expenses & Insurance',
      type: 'Asset',
      subtype: 'Prepaid Assets',
      normalBalance: 'Debit',
      description: 'Advance payments for services not yet incurred',
      isActive: true,
    },
    {
      id: `${companyId}-acc-1510`,
      companyId,
      code: '1510',
      name: 'Equipment, Tech & Furniture',
      type: 'Asset',
      subtype: 'Property, Plant & Equipment',
      normalBalance: 'Debit',
      description: 'Fixed physical assets and technology hardware',
      isActive: true,
    },

    // LIABILITIES (2000 - 2999) - Strictly Accounts Payable, Long Term Payable, Accrued Expenses, Unearned Revenue
    {
      id: `${companyId}-acc-2010`,
      companyId,
      code: '2010',
      name: 'Accounts Payable (A/P)',
      type: 'Liability',
      subtype: 'Accounts Payable',
      normalBalance: 'Credit',
      description: 'Vendor bills and invoices owed by company',
      isActive: true,
      isSystem: true,
    },
    {
      id: `${companyId}-acc-2020`,
      companyId,
      code: '2020',
      name: 'Accrued Operating & Payroll Expenses',
      type: 'Liability',
      subtype: 'Accrued Expenses',
      normalBalance: 'Credit',
      description: 'Accrued payroll, utilities, and operating expenses payable',
      isActive: true,
    },
    {
      id: `${companyId}-acc-2030`,
      companyId,
      code: '2030',
      name: 'Unearned Revenue & Client Advances',
      type: 'Liability',
      subtype: 'Unearned Revenue',
      normalBalance: 'Credit',
      description: 'Advances and deposits from clients prior to service delivery',
      isActive: true,
    },
    {
      id: `${companyId}-acc-2510`,
      companyId,
      code: '2510',
      name: 'Commercial Bank Loan / Long-Term Note Payable',
      type: 'Liability',
      subtype: 'Long Term Payable',
      normalBalance: 'Credit',
      description: 'Long-term commercial bank financing note payable',
      isActive: true,
    },

    // EQUITY (3000 - 3999)
    {
      id: `${companyId}-acc-3010`,
      companyId,
      code: '3010',
      name: entityType === 'Corporation' ? 'Common Stock & Paid-In Capital' : "Owner's Equity & Contributions",
      type: 'Equity',
      subtype: 'Owner Equity',
      normalBalance: 'Credit',
      description: 'Initial capital contributed by owners/shareholders',
      isActive: true,
    },
    {
      id: `${companyId}-acc-3020`,
      companyId,
      code: '3020',
      name: 'Retained Earnings',
      type: 'Equity',
      subtype: 'Retained Earnings',
      normalBalance: 'Credit',
      description: 'Cumulative prior earnings retained in entity',
      isActive: true,
      isSystem: true,
    },

    // REVENUE (4000 - 4999)
    {
      id: `${companyId}-acc-4010`,
      companyId,
      code: '4010',
      name: 'Core Services & Product Revenue',
      type: 'Revenue',
      subtype: 'Operating Revenue',
      normalBalance: 'Credit',
      description: 'Primary operating customer billings and contracts',
      isActive: true,
    },
    {
      id: `${companyId}-acc-4020`,
      companyId,
      code: '4020',
      name: 'Consulting & Retainer Fees',
      type: 'Revenue',
      subtype: 'Operating Revenue',
      normalBalance: 'Credit',
      description: 'Advisory, maintenance, and recurring retainer income',
      isActive: true,
    },
    {
      id: `${companyId}-acc-4090`,
      companyId,
      code: '4090',
      name: 'Interest & Miscellaneous Income',
      type: 'Revenue',
      subtype: 'Other Income',
      normalBalance: 'Credit',
      description: 'Yield on savings and incidental income',
      isActive: true,
    },

    // COST OF GOODS SOLD (5000 - 5999)
    {
      id: `${companyId}-acc-5010`,
      companyId,
      code: '5010',
      name: 'Cost of Goods Sold / Materials',
      type: 'Expense',
      subtype: 'Cost of Goods Sold',
      normalBalance: 'Debit',
      description: 'Direct production costs and materials for sold goods',
      isActive: true,
    },
    {
      id: `${companyId}-acc-5020`,
      companyId,
      code: '5020',
      name: 'Subcontractors & Direct Labor',
      type: 'Expense',
      subtype: 'Cost of Goods Sold',
      normalBalance: 'Debit',
      description: 'Direct contractors tied to client deliverables',
      isActive: true,
    },

    // OPERATING EXPENSES (6000 - 6999)
    {
      id: `${companyId}-acc-6010`,
      companyId,
      code: '6010',
      name: 'Salaries, Wages & Benefits',
      type: 'Expense',
      subtype: 'Payroll Expense',
      normalBalance: 'Debit',
      description: 'Staff payroll, health benefits, and compensation',
      isActive: true,
    },
    {
      id: `${companyId}-acc-6020`,
      companyId,
      code: '6020',
      name: 'Office Rent & Facilities',
      type: 'Expense',
      subtype: 'Rent & Utilities',
      normalBalance: 'Debit',
      description: 'Office leasing, utilities, and building maintenance',
      isActive: true,
    },
    {
      id: `${companyId}-acc-6030`,
      companyId,
      code: '6030',
      name: 'Software, SaaS & Cloud Infrastructure',
      type: 'Expense',
      subtype: 'Operating Expense',
      normalBalance: 'Debit',
      description: 'AWS, Google Cloud, GitHub, Productivity tools',
      isActive: true,
    },
    {
      id: `${companyId}-acc-6040`,
      companyId,
      code: '6040',
      name: 'Marketing, Advertising & PR',
      type: 'Expense',
      subtype: 'Operating Expense',
      normalBalance: 'Debit',
      description: 'Digital advertising, campaigns, and sponsorships',
      isActive: true,
    },
    {
      id: `${companyId}-acc-6050`,
      companyId,
      code: '6050',
      name: 'Legal, CPA & Professional Fees',
      type: 'Expense',
      subtype: 'Professional Services',
      normalBalance: 'Debit',
      description: 'Accounting, tax preparation, and corporate legal counsel',
      isActive: true,
    },
    {
      id: `${companyId}-acc-6060`,
      companyId,
      code: '6060',
      name: 'Insurance & Licenses',
      type: 'Expense',
      subtype: 'Operating Expense',
      normalBalance: 'Debit',
      description: 'General liability, cyber, and business operational licenses',
      isActive: true,
    },
    {
      id: `${companyId}-acc-6070`,
      companyId,
      code: '6070',
      name: 'Bank & Merchant Processing Fees',
      type: 'Expense',
      subtype: 'Operating Expense',
      normalBalance: 'Debit',
      description: 'Credit card transaction charges and wire fees',
      isActive: true,
    },
  ];
}

export const initialCompanies: CompanyProfile[] = [
  {
    id: 'comp-apex-tech',
    name: 'Apex Tech Solutions LLC',
    tradeName: 'Apex Cloud Systems',
    taxId: '084-391-024-00000',
    entityType: 'Sole Proprietorship',
    currency: 'USD',
    currencySymbol: '$',
    fiscalYearEnd: 'December 31',
    accountingMethod: 'Accrual',
    email: 'finance@apextechsolutions.io',
    phone: '+1 (415) 890-3210',
    address: {
      street: '450 Mission Street, Suite 1400',
      city: 'San Francisco',
      state: 'CA',
      zip: '94105',
      country: 'United States',
    },
    defaultTaxRate: 8.5,
    brandColor: '#0284c7', // Sky blue
    createdAt: '2026-01-01T08:00:00Z',
    notes: 'Enterprise cloud consulting & B2B SaaS engineering firm. High-margin service entity.',
    soleProprietorInfo: {
      ownerName: 'Alex Mercer',
      beginningCapital: 45000,
      additionalInvestment: 5000,
      drawings: 12000,
    },
  },
  {
    id: 'comp-vanguard-retail',
    name: 'Vanguard Retail & Logistics Corp',
    tradeName: 'Vanguard Global Supply',
    taxId: '036-849-201-00001',
    entityType: 'Corporation',
    currency: 'USD',
    currencySymbol: '$',
    fiscalYearEnd: 'December 31',
    accountingMethod: 'Accrual',
    email: 'accounting@vanguardretail.com',
    phone: '+1 (312) 555-7820',
    address: {
      street: '1200 West Fulton Market',
      city: 'Chicago',
      state: 'IL',
      zip: '60607',
      country: 'United States',
    },
    defaultTaxRate: 7.25,
    brandColor: '#059669', // Emerald
    createdAt: '2026-01-05T09:30:00Z',
    notes: 'National wholesale commercial distributor with warehouse inventory, physical equipment, and high-volume freight.',
    corporationInfo: {
      authorizedCapitalStock: 1000000, // $1,000,000 Authorized Capital Stock
      parValuePerShare: 10,
      authorizedShares: 100000,
      paidUpCapital: 250000, // $250,000 Paid-Up Capital (used as Share Capital)
      subscribedCapital: 250000,
      appropriatedRetainedEarnings: 35000, // Reserve for warehouse expansion
      unappropriatedRetainedEarnings: 52000, // Retained Earnings available for dividend declaration
      dividendsDeclared: 15000,
    },
  },
  {
    id: 'comp-nexus-partners',
    name: 'Nexus Professional Legal & CPA Partners',
    tradeName: 'Nexus Advisors LLP',
    taxId: '048-291-773-00000',
    entityType: 'Partnership',
    currency: 'USD',
    currencySymbol: '$',
    fiscalYearEnd: 'December 31',
    accountingMethod: 'Accrual',
    email: 'partners@nexusadvisors.com',
    phone: '+1 (212) 555-9180',
    address: {
      street: '100 Wall Street, 24th Floor',
      city: 'New York',
      state: 'NY',
      zip: '10005',
      country: 'United States',
    },
    defaultTaxRate: 8.875,
    brandColor: '#7c3aed', // Violet
    createdAt: '2026-01-10T10:00:00Z',
    notes: 'General Professional Partnership specializing in corporate advisory & audit. 60/40 profit sharing agreement.',
    partnershipInfo: {
      partners: [
        {
          id: 'part-1',
          name: 'Eleanor Vance, CPA',
          profitSharePercentage: 60,
          beginningCapital: 60000,
          additionalInvestment: 10000,
          drawings: 8000,
        },
        {
          id: 'part-2',
          name: 'Marcus Thorne, Esq.',
          profitSharePercentage: 40,
          beginningCapital: 40000,
          additionalInvestment: 5000,
          drawings: 5000,
        },
      ],
    },
  },
];

export function getInitialSeedJournalEntries(companyId: string): JournalEntry[] {
  if (companyId === 'comp-apex-tech') {
    return [
      {
        id: 'je-apex-001',
        companyId: 'comp-apex-tech',
        entryNumber: 'JE-2026-001',
        date: '2026-01-02',
        description: "Initial Owner Equity Capital Contribution",
        reference: 'WIRE-FOUNDER-01',
        sourceType: 'Opening_Balance',
        status: 'Posted',
        createdAt: '2026-01-02T10:00:00Z',
        lines: [
          {
            id: 'line-1',
            accountId: 'comp-apex-tech-acc-1010',
            accountCode: '1010',
            accountName: 'Operating Checking Account',
            debit: 150000,
            credit: 0,
            memo: 'Initial seed capital deposit',
          },
          {
            id: 'line-2',
            accountId: 'comp-apex-tech-acc-3010',
            accountCode: '3010',
            accountName: "Owner's Equity & Contributions",
            debit: 0,
            credit: 150000,
            memo: 'Paid-in member equity',
          },
        ],
      },
      {
        id: 'je-apex-002',
        companyId: 'comp-apex-tech',
        entryNumber: 'JE-2026-002',
        date: '2026-01-08',
        description: 'Purchase of High-Performance Developer MacBooks & Workstations',
        reference: 'APPLE-INV-9921',
        sourceType: 'Manual',
        status: 'Posted',
        createdAt: '2026-01-08T14:30:00Z',
        lines: [
          {
            id: 'line-3',
            accountId: 'comp-apex-tech-acc-1510',
            accountCode: '1510',
            accountName: 'Equipment, Tech & Furniture',
            debit: 18500,
            credit: 0,
            memo: '5x M3 Max Developer Laptops',
          },
          {
            id: 'line-4',
            accountId: 'comp-apex-tech-acc-1010',
            accountCode: '1010',
            accountName: 'Operating Checking Account',
            debit: 0,
            credit: 18500,
            memo: 'Direct checking debit',
          },
        ],
      },
      {
        id: 'je-apex-003',
        companyId: 'comp-apex-tech',
        entryNumber: 'JE-2026-003',
        date: '2026-01-15',
        description: 'Enterprise Cloud Migration Contract Billing - Nexus Corp',
        reference: 'INV-1001',
        sourceType: 'Invoice',
        status: 'Posted',
        createdAt: '2026-01-15T11:00:00Z',
        lines: [
          {
            id: 'line-5',
            accountId: 'comp-apex-tech-acc-1030',
            accountCode: '1030',
            accountName: 'Accounts Receivable (A/R)',
            debit: 65000,
            credit: 0,
            memo: 'Milestone 1 Deliverable billed to Nexus Corp',
          },
          {
            id: 'line-6',
            accountId: 'comp-apex-tech-acc-4010',
            accountCode: '4010',
            accountName: 'Core Services & Product Revenue',
            debit: 0,
            credit: 65000,
            memo: 'Cloud architecture & migration fees',
          },
        ],
      },
      {
        id: 'je-apex-004',
        companyId: 'comp-apex-tech',
        entryNumber: 'JE-2026-004',
        date: '2026-01-25',
        description: 'Monthly Engineering & Product Staff Payroll Run',
        reference: 'PAYROLL-JAN-1',
        sourceType: 'Manual',
        status: 'Posted',
        createdAt: '2026-01-25T16:00:00Z',
        lines: [
          {
            id: 'line-7',
            accountId: 'comp-apex-tech-acc-6010',
            accountCode: '6010',
            accountName: 'Salaries, Wages & Benefits',
            debit: 28000,
            credit: 0,
            memo: 'January engineering compensation',
          },
          {
            id: 'line-8',
            accountId: 'comp-apex-tech-acc-2030',
            accountCode: '2030',
            accountName: 'Accrued Payroll & Withholding Taxes',
            debit: 0,
            credit: 6000,
            memo: 'Payroll taxes withheld payable',
          },
          {
            id: 'line-9',
            accountId: 'comp-apex-tech-acc-1010',
            accountCode: '1010',
            accountName: 'Operating Checking Account',
            debit: 0,
            credit: 22000,
            memo: 'Net direct deposits to staff',
          },
        ],
      },
      {
        id: 'je-apex-005',
        companyId: 'comp-apex-tech',
        entryNumber: 'JE-2026-005',
        date: '2026-01-31',
        description: 'Monthly Cloud Infrastructure & Tooling Expenses',
        reference: 'BILL-AWS-01',
        sourceType: 'Bill',
        status: 'Posted',
        createdAt: '2026-01-31T09:15:00Z',
        lines: [
          {
            id: 'line-10',
            accountId: 'comp-apex-tech-acc-6030',
            accountCode: '6030',
            accountName: 'Software, SaaS & Cloud Infrastructure',
            debit: 4250,
            credit: 0,
            memo: 'AWS hosting & GitHub Enterprise',
          },
          {
            id: 'line-11',
            accountId: 'comp-apex-tech-acc-2010',
            accountCode: '2010',
            accountName: 'Accounts Payable (A/P)',
            debit: 0,
            credit: 4250,
            memo: 'Accrued bill due Feb 15',
          },
        ],
      },
      {
        id: 'je-apex-006',
        companyId: 'comp-apex-tech',
        entryNumber: 'JE-2026-006',
        date: '2026-02-05',
        description: 'Customer Payment Received from Nexus Corp for INV-1001',
        reference: 'WIRE-RCV-NEXUS',
        sourceType: 'Payment',
        status: 'Posted',
        createdAt: '2026-02-05T13:00:00Z',
        lines: [
          {
            id: 'line-12',
            accountId: 'comp-apex-tech-acc-1010',
            accountCode: '1010',
            accountName: 'Operating Checking Account',
            debit: 65000,
            credit: 0,
            memo: 'Payment in full for INV-1001',
          },
          {
            id: 'line-13',
            accountId: 'comp-apex-tech-acc-1030',
            accountCode: '1030',
            accountName: 'Accounts Receivable (A/R)',
            debit: 0,
            credit: 65000,
            memo: 'Clear receivable for Nexus Corp',
          },
        ],
      },
      {
        id: 'je-apex-007',
        companyId: 'comp-apex-tech',
        entryNumber: 'JE-2026-007',
        date: '2026-02-14',
        description: 'Monthly Retainer & Advisory Billing - Horizon Health',
        reference: 'INV-1002',
        sourceType: 'Invoice',
        status: 'Posted',
        createdAt: '2026-02-14T10:00:00Z',
        lines: [
          {
            id: 'line-14',
            accountId: 'comp-apex-tech-acc-1030',
            accountCode: '1030',
            accountName: 'Accounts Receivable (A/R)',
            debit: 42000,
            credit: 0,
            memo: 'Q1 retainer billing to Horizon Health',
          },
          {
            id: 'line-15',
            accountId: 'comp-apex-tech-acc-4020',
            accountCode: '4020',
            accountName: 'Consulting & Retainer Fees',
            debit: 0,
            credit: 42000,
            memo: 'HealthTech HIPAA Compliance architecture',
          },
        ],
      },
    ];
  }

  // Vanguard Retail Seed Entries
  return [
    {
      id: 'je-vang-001',
      companyId: 'comp-vanguard-retail',
      entryNumber: 'JE-2026-001',
      date: '2026-01-05',
      description: 'Shareholder Capital Contribution & Paid-in Surplus',
      reference: 'CORP-ISSUANCE-01',
      sourceType: 'Opening_Balance',
      status: 'Posted',
      createdAt: '2026-01-05T10:00:00Z',
      lines: [
        {
          id: 'v-line-1',
          accountId: 'comp-vanguard-retail-acc-1010',
          accountCode: '1010',
          accountName: 'Operating Checking Account',
          debit: 250000,
          credit: 0,
          memo: 'Capital deposited in primary treasury',
        },
        {
          id: 'v-line-2',
          accountId: 'comp-vanguard-retail-acc-3010',
          accountCode: '3010',
          accountName: 'Common Stock & Paid-In Capital',
          debit: 0,
          credit: 250000,
          memo: 'Series Common stock issued',
        },
      ],
    },
    {
      id: 'je-vang-002',
      companyId: 'comp-vanguard-retail',
      entryNumber: 'JE-2026-002',
      date: '2026-01-12',
      description: 'Bulk Warehouse Inventory Stock Purchase - Global Freight',
      reference: 'PO-2026-88',
      sourceType: 'Bill',
      status: 'Posted',
      createdAt: '2026-01-12T11:00:00Z',
      lines: [
        {
          id: 'v-line-3',
          accountId: 'comp-vanguard-retail-acc-1050',
          accountCode: '1050',
          accountName: 'Merchandise Inventory',
          debit: 85000,
          credit: 0,
          memo: 'Container load commercial supplies',
        },
        {
          id: 'v-line-4',
          accountId: 'comp-vanguard-retail-acc-2010',
          accountCode: '2010',
          accountName: 'Accounts Payable (A/P)',
          debit: 0,
          credit: 85000,
          memo: 'Net 30 terms with Global Freight suppliers',
        },
      ],
    },
    {
      id: 'je-vang-003',
      companyId: 'comp-vanguard-retail',
      entryNumber: 'JE-2026-003',
      date: '2026-01-20',
      description: 'Wholesale Shipment Sold & Delivered to Midwest Distributors',
      reference: 'INV-VG-501',
      sourceType: 'Invoice',
      status: 'Posted',
      createdAt: '2026-01-20T15:00:00Z',
      lines: [
        {
          id: 'v-line-5',
          accountId: 'comp-vanguard-retail-acc-1030',
          accountCode: '1030',
          accountName: 'Accounts Receivable (A/R)',
          debit: 110000,
          credit: 0,
          memo: 'Billed to Midwest Distributors',
        },
        {
          id: 'v-line-6',
          accountId: 'comp-vanguard-retail-acc-4010',
          accountCode: '4010',
          accountName: 'Core Services & Product Revenue',
          debit: 0,
          credit: 110000,
          memo: 'Product sales revenue',
        },
      ],
    },
    {
      id: 'je-vang-004',
      companyId: 'comp-vanguard-retail',
      entryNumber: 'JE-2026-004',
      date: '2026-01-20',
      description: 'Cost of Goods Sold Recognition for Wholesale Order INV-VG-501',
      reference: 'COGS-ADJ-501',
      sourceType: 'Manual',
      status: 'Posted',
      createdAt: '2026-01-20T15:05:00Z',
      lines: [
        {
          id: 'v-line-7',
          accountId: 'comp-vanguard-retail-acc-5010',
          accountCode: '5010',
          accountName: 'Cost of Goods Sold / Materials',
          debit: 62000,
          credit: 0,
          memo: 'Inventory cost matching sales delivery',
        },
        {
          id: 'v-line-8',
          accountId: 'comp-vanguard-retail-acc-1050',
          accountCode: '1050',
          accountName: 'Merchandise Inventory',
          debit: 0,
          credit: 62000,
          memo: 'Inventory reduction on shipment',
        },
      ],
    },
    {
      id: 'je-vang-005',
      companyId: 'comp-vanguard-retail',
      entryNumber: 'JE-2026-005',
      date: '2026-01-30',
      description: 'Warehouse Facility Lease & Utility Payments',
      reference: 'LEASE-JAN-2026',
      sourceType: 'Manual',
      status: 'Posted',
      createdAt: '2026-01-30T10:00:00Z',
      lines: [
        {
          id: 'v-line-9',
          accountId: 'comp-vanguard-retail-acc-6020',
          accountCode: '6020',
          accountName: 'Office Rent & Facilities',
          debit: 14500,
          credit: 0,
          memo: 'Warehouse rent Chicago Fulton location',
        },
        {
          id: 'v-line-10',
          accountId: 'comp-vanguard-retail-acc-1010',
          accountCode: '1010',
          accountName: 'Operating Checking Account',
          debit: 0,
          credit: 14500,
          memo: 'ACH transfer to Fulton Properties',
        },
      ],
    },
  ];

  if (companyId === 'comp-nexus-partners') {
    return [
      {
        id: 'je-nexus-001',
        companyId: 'comp-nexus-partners',
        entryNumber: 'JE-2026-001',
        date: '2026-01-05',
        description: 'Initial Partner Capital Contributions (Eleanor Vance 60%, Marcus Thorne 40%)',
        reference: 'PARTNER-AGR-2026',
        sourceType: 'Opening_Balance',
        status: 'Posted',
        createdAt: '2026-01-05T09:00:00Z',
        lines: [
          {
            id: 'n-line-1',
            accountId: 'comp-nexus-partners-acc-1010',
            accountCode: '1010',
            accountName: 'Operating Checking Account',
            debit: 100000,
            credit: 0,
            memo: 'Initial partnership bank deposit',
          },
          {
            id: 'n-line-2',
            accountId: 'comp-nexus-partners-acc-3010',
            accountCode: '3010',
            accountName: "Owner's Equity & Contributions",
            debit: 0,
            credit: 100000,
            memo: 'Partner Capital: Eleanor $60,000 (60%) | Marcus $40,000 (40%)',
          },
        ],
      },
      {
        id: 'je-nexus-002',
        companyId: 'comp-nexus-partners',
        entryNumber: 'JE-2026-002',
        date: '2026-01-18',
        description: 'Corporate Client Audit & Retainer Billings',
        reference: 'INV-NX-101',
        sourceType: 'Invoice',
        status: 'Posted',
        createdAt: '2026-01-18T11:00:00Z',
        lines: [
          {
            id: 'n-line-3',
            accountId: 'comp-nexus-partners-acc-1030',
            accountCode: '1030',
            accountName: 'Accounts Receivable (A/R)',
            debit: 45000,
            credit: 0,
            memo: 'Retainer receivable from Crestline Capital',
          },
          {
            id: 'n-line-4',
            accountId: 'comp-nexus-partners-acc-4010',
            accountCode: '4010',
            accountName: 'Core Services & Product Revenue',
            debit: 0,
            credit: 45000,
            memo: 'Audit and advisory fees',
          },
        ],
      },
      {
        id: 'je-nexus-003',
        companyId: 'comp-nexus-partners',
        entryNumber: 'JE-2026-003',
        date: '2026-01-28',
        description: 'Partner Drawings Distribution (Eleanor Vance & Marcus Thorne)',
        reference: 'DRAW-JAN-2026',
        sourceType: 'Manual',
        status: 'Posted',
        createdAt: '2026-01-28T16:00:00Z',
        lines: [
          {
            id: 'n-line-5',
            accountId: 'comp-nexus-partners-acc-3010',
            accountCode: '3010',
            accountName: "Owner's Equity & Contributions",
            debit: 13000,
            credit: 0,
            memo: 'Partner Draws: Eleanor Vance $8,000 | Marcus Thorne $5,000',
          },
          {
            id: 'n-line-6',
            accountId: 'comp-nexus-partners-acc-1010',
            accountCode: '1010',
            accountName: 'Operating Checking Account',
            debit: 0,
            credit: 13000,
            memo: 'Disbursement of January partner drawings',
          },
        ],
      },
    ];
  }
}

export function getInitialSeedTransactions(companyId: string): Transaction[] {
  if (companyId === 'comp-apex-tech') {
    return [
      {
        id: 'tx-apex-01',
        companyId: 'comp-apex-tech',
        type: 'Invoice',
        number: 'INV-1001',
        date: '2026-01-15',
        dueDate: '2026-02-15',
        contactName: 'Nexus Enterprise Corp',
        contactEmail: 'billing@nexuscorp.com',
        amount: 65000,
        status: 'Paid',
        categoryAccountId: 'comp-apex-tech-acc-4010',
        bankAccountId: 'comp-apex-tech-acc-1010',
        description: 'Enterprise Cloud Architecture & Migration Milestone 1',
        items: [
          {
            id: 'item-1',
            description: 'Cloud Infrastructure Design & IaC setup',
            quantity: 1,
            unitPrice: 40000,
            total: 40000,
          },
          {
            id: 'item-2',
            description: 'Microservices Data Migration',
            quantity: 1,
            unitPrice: 25000,
            total: 25000,
          },
        ],
        linkedJournalEntryId: 'je-apex-003',
        createdAt: '2026-01-15T11:00:00Z',
      },
      {
        id: 'tx-apex-02',
        companyId: 'comp-apex-tech',
        type: 'Invoice',
        number: 'INV-1002',
        date: '2026-02-14',
        dueDate: '2026-03-15',
        contactName: 'Horizon Health Systems',
        contactEmail: 'accounts@horizonhealth.org',
        amount: 42000,
        status: 'Sent',
        categoryAccountId: 'comp-apex-tech-acc-4020',
        description: 'HIPAA Cloud Security & Architecture Retainer',
        items: [
          {
            id: 'item-3',
            description: 'Q1 Security Audit & Architecture Advisory',
            quantity: 1,
            unitPrice: 42000,
            total: 42000,
          },
        ],
        linkedJournalEntryId: 'je-apex-007',
        createdAt: '2026-02-14T10:00:00Z',
      },
      {
        id: 'tx-apex-03',
        companyId: 'comp-apex-tech',
        type: 'Bill',
        number: 'BILL-AWS-01',
        date: '2026-01-31',
        dueDate: '2026-02-15',
        contactName: 'Amazon Web Services LLC',
        contactEmail: 'aws-receivables@amazon.com',
        amount: 4250,
        status: 'Unpaid',
        categoryAccountId: 'comp-apex-tech-acc-6030',
        description: 'Dedicated compute cluster & storage instances',
        items: [
          {
            id: 'item-4',
            description: 'EC2 & RDS Multi-AZ instances',
            quantity: 1,
            unitPrice: 4250,
            total: 4250,
          },
        ],
        linkedJournalEntryId: 'je-apex-005',
        createdAt: '2026-01-31T09:15:00Z',
      },
    ];
  }

  return [
    {
      id: 'tx-vang-01',
      companyId: 'comp-vanguard-retail',
      type: 'Invoice',
      number: 'INV-VG-501',
      date: '2026-01-20',
      dueDate: '2026-02-20',
      contactName: 'Midwest Distributors Network',
      contactEmail: 'orders@midwestdist.com',
      amount: 110000,
      status: 'Sent',
      categoryAccountId: 'comp-vanguard-retail-acc-4010',
      description: 'Bulk commercial shipment batch #49',
      items: [
        {
          id: 'v-item-1',
          description: 'Industrial Safety Equipment Grade A (500 units)',
          quantity: 500,
          unitPrice: 220,
          total: 110000,
        },
      ],
      linkedJournalEntryId: 'je-vang-003',
      createdAt: '2026-01-20T15:00:00Z',
    },
    {
      id: 'tx-vang-02',
      companyId: 'comp-vanguard-retail',
      type: 'Bill',
      number: 'BILL-GF-104',
      date: '2026-01-12',
      dueDate: '2026-02-12',
      contactName: 'Global Freight & Manufacturing',
      contactEmail: 'finance@globalfreightcorp.com',
      amount: 85000,
      status: 'Unpaid',
      categoryAccountId: 'comp-vanguard-retail-acc-1050',
      description: 'Wholesale materials shipment import batch',
      items: [
        {
          id: 'v-item-2',
          description: 'Commercial Inventory Containers',
          quantity: 1,
          unitPrice: 85000,
          total: 85000,
        },
      ],
      linkedJournalEntryId: 'je-vang-002',
      createdAt: '2026-01-12T11:00:00Z',
    },
  ];
}

export function getInitialSeedInventoryItems(companyId: string): InventoryItem[] {
  return [
    {
      id: `${companyId}-inv-001`,
      companyId,
      sku: 'SKU-ENT-101',
      name: 'High-Density Commercial Server Rack',
      description: '42U Standard 19-inch steel equipment rack enclosure',
      category: 'Hardware & Infrastructure',
      unit: 'units',
      unitCost: 650,
      unitPrice: 1200,
      quantityOnHand: 40,
      reorderPoint: 10,
      createdAt: '2026-01-05T09:00:00Z',
    },
    {
      id: `${companyId}-inv-002`,
      companyId,
      sku: 'SKU-ENT-102',
      name: 'Managed Gigabit Network Switch 48-Port',
      description: 'Layer 3 PoE enterprise rackmount network switch',
      category: 'Networking Equipment',
      unit: 'units',
      unitCost: 420,
      unitPrice: 850,
      quantityOnHand: 65,
      reorderPoint: 15,
      createdAt: '2026-01-06T10:00:00Z',
    },
    {
      id: `${companyId}-inv-003`,
      companyId,
      sku: 'SKU-ENT-103',
      name: 'Enterprise Uninterruptible Power Supply (UPS) 3000VA',
      description: 'Pure sine wave online double-conversion backup power',
      category: 'Power & Protection',
      unit: 'units',
      unitCost: 550,
      unitPrice: 1050,
      quantityOnHand: 28,
      reorderPoint: 8,
      createdAt: '2026-01-07T11:30:00Z',
    },
    {
      id: `${companyId}-inv-004`,
      companyId,
      sku: 'SKU-ENT-104',
      name: 'Cat6A Shielded Bulk Ethernet Cable 1000ft',
      description: 'Spool of 10Gbps 23AWG CMR rated solid copper cable',
      category: 'Cabling & Peripherals',
      unit: 'spools',
      unitCost: 110,
      unitPrice: 220,
      quantityOnHand: 85,
      reorderPoint: 20,
      createdAt: '2026-01-08T14:00:00Z',
    },
    {
      id: `${companyId}-inv-005`,
      companyId,
      sku: 'SKU-ENT-105',
      name: 'Fiber Optic Transceiver Module 10G SFP+',
      description: 'Single-mode optical LC connector transceiver 1310nm',
      category: 'Networking Equipment',
      unit: 'pcs',
      unitCost: 35,
      unitPrice: 75,
      quantityOnHand: 140,
      reorderPoint: 30,
      createdAt: '2026-01-09T16:00:00Z',
    },
  ];
}
